const tagNames = [
  'Array',
  'Hash Table',
  'Linked List',
  'Math',
  'Two Pointers',
  'String',
  'Binary Search',
  'Divide And Conquer',
  'Dynamic Programming',
  'Back Tracking',
  'Stack',
  'Heap',
  'Greedy',
  'Sort',
  'Bit Manipulation',
  'Trees',
  'Depth-first Search',
  'Breath-first Search',
  'Union Find',
  'Graph',
  'Design',
  'Topological Sort',
  'Trie',
  'Binary Index Tree',
  'Segment Tree',
  'Binary Search Tree',
  'Recursion',
  'Brainteaser',
  'Memoization',
  'Queue',
  'Minimax',
  'Reservoir Sampling',
  'Ordered Map',
  'Geometry',
  'Random',
  'Rejection Sampling',
  'Sliding Window',
  'Line Sweep',
  'Rolling Hash',
  'Suffix Array',
  'Dequeue',
  'OOP',
  'Meet in the Middle',
];

module.exports = tagNames;
